console.group(Screen);
console.log(screen);
console.log(screen.availHeight);
console.log(screen.availWidth);
console.log(screen.colorDepth);
console.log(screen.pixelDepth);
console.log(screen.height);
console.log(screen.width);
console.groupEnd();